In [ ]:
import pickle
import numpy as p

In [11]:
with open(" metr-la-by-disp_fil-with-alpah_filter0_1.pkl", 'rb') as f:
    adj_mx = pickle.load(f, encoding='latin1')
    print(adj_mx)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
np.load